version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: vollmed_api_db
    networks:
      - vollmed-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  vollmed-net:
    driver: bridge
