version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-vollmed
    restart: always
    platform: linux/amd64
    tty: false
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
    ports:
      - 3306:3306